# Generated by Django 2.0.6 on 2018-06-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Collaborator Name', max_length=255)),
                ('url', models.URLField()),
                ('twitter', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=255)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbncreative_cms.Collaborator')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbncreative_cms.Project'),
        ),
    ]
