# Generated by Django 2.0.6 on 2018-06-26 12:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('body', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Collaborator Name', max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('twitter', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=255)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bbncreative_cms.Collaborator')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Project', max_length=255)),
                ('url_name', models.SlugField(allow_unicode=True, default='new-project', max_length=255)),
                ('date_complete', models.DateField(default=datetime.date.today)),
                ('is_complete', models.BooleanField(default=False)),
                ('project_url', models.URLField(default='https://bbncreative.co', max_length=255)),
                ('client_name', models.CharField(default='New Client', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddedAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bbncreative_cms.Asset')),
                ('embed_code', models.TextField(max_length=5000)),
            ],
            bases=('bbncreative_cms.asset',),
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bbncreative_cms.Asset')),
                ('alt', models.TextField(max_length=5000)),
                ('img', models.FileField(max_length=255, upload_to='media/%Y/%m/%d')),
            ],
            bases=('bbncreative_cms.asset',),
        ),
        migrations.AddField(
            model_name='credit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbncreative_cms.Project'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbncreative_cms.Project'),
        ),
    ]
