# Generated by Django 2.0.6 on 2018-07-02 20:30

import bbncreative_cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncreative_cms', '0005_auto_20180702_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date_complete', '-is_complete']},
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='img',
            field=models.ImageField(max_length=255, upload_to=bbncreative_cms.models.get_file_path),
        ),
    ]
