# Generated by Django 2.0.6 on 2018-07-05 13:27

import bbncreative_cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncreative_cms', '0007_auto_20180705_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hero',
            field=models.ImageField(blank=True, max_length=255, upload_to=bbncreative_cms.models.get_file_path),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, max_length=255, upload_to=bbncreative_cms.models.get_file_path),
        ),
    ]
