# Generated by Django 2.0.7 on 2018-07-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0010_auto_20180711_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brand_color_1',
            field=models.CharField(default='ffffff', max_length=6),
        ),
        migrations.AddField(
            model_name='project',
            name='brand_color_2',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
