# Generated by Django 2.0.7 on 2018-07-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0011_auto_20180724_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='menu_icon_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
