# Generated by Django 2.0.7 on 2018-07-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0012_feed_menu_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='protected',
            field=models.BooleanField(default=True),
        ),
    ]
