# Generated by Django 2.0.7 on 2018-07-31 12:16

from django.db import migrations, models

import bbncreative_cms.models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0013_feed_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='brand_color_1',
            field=models.CharField(default='455a64', max_length=6),
        ),
        migrations.AddField(
            model_name='feed',
            name='brand_color_2',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='feed',
            name='hero',
            field=models.ImageField(blank=True, max_length=255, upload_to=bbncreative_cms.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='brand_color_1',
            field=models.CharField(default='455a64', max_length=6),
        ),
    ]
