# Generated by Django 2.1 on 2018-08-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0016_imageasset_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedasset',
            name='aspect_ratio',
            field=models.CharField(choices=[('VL', '16:9 Wide'), ('VP', '9:16 Tall'), ('IG', 'Instagram Post')],
                                   default='VL', max_length=2),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='aspect_ratio',
            field=models.CharField(
                choices=[('SQ', 'Square'), ('W1', '4:3 Wide'), ('W2', '3:2 Wide'), ('W3', '16:9 Wide'),
                         ('T1', '3:4 Tall'), ('T2', '2:3 Tall'), ('T3', '9:16 Tall')], default='W1', max_length=2),
        ),
    ]
