# Generated by Django 2.1 on 2018-08-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0017_auto_20180814_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='brand_color_1',
            field=models.CharField(default='e8185f', max_length=6),
        ),
        migrations.AlterField(
            model_name='feed',
            name='brand_color_2',
            field=models.CharField(blank=True, default='ff1a36', max_length=6),
        ),
    ]
