# Generated by Django 2.1 on 2018-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0018_auto_20180816_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='menu_name',
            field=models.CharField(default='New Feed', max_length=15),
        ),
        migrations.AddField(
            model_name='feed',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
