# Generated by Django 2.1 on 2018-08-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0019_auto_20180818_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='menu_name',
            field=models.CharField(default='New Project', max_length=15),
        ),
    ]
