# Generated by Django 3.0.3 on 2020-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncreative_cms', '0026_auto_20190105_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='twitter',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
