# Generated by Django 3.0.3 on 2020-04-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncreative_cms', '0027_auto_20200404_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url_name',
            field=models.SlugField(allow_unicode=True, default='new-feed', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_name',
            field=models.SlugField(allow_unicode=True, default='new-project', max_length=255, unique=True),
        ),
    ]
