# Generated by Django 2.0.6 on 2018-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncreative_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedasset',
            name='importance',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='img',
            field=models.ImageField(max_length=255, upload_to='ea56f8d1-fbe4-4083-ba9f-94cf5c2ccbfa/'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='importance',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
