# Generated by Django 2.0.6 on 2018-07-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncreative_cms', '0004_auto_20180702_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_complete']},
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='img',
            field=models.ImageField(max_length=255, upload_to='<function uuid4 at 0x000001D0D0427598>/'),
        ),
    ]
