# Generated by Django 2.1 on 2018-08-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0020_project_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bio',
            field=models.TextField(default='[Project Bio]', max_length=200),
        ),
    ]
