# Generated by Django 2.1 on 2018-08-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bbncreative_cms', '0023_auto_20180830_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-date_time_updated']},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='feed',
            name='date_time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
