# Generated by Django 2.1.3 on 2018-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbncreative_cms', '0024_auto_20180830_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedasset',
            name='embed_code',
            field=models.TextField(max_length=10000),
        ),
    ]
