# Generated by Django 2.1.3 on 2019-01-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbncreative_cms', '0025_auto_20181111_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedasset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbncreative_cms.Project'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbncreative_cms.Project'),
        ),
        migrations.AlterField(
            model_name='textasset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbncreative_cms.Project'),
        ),
    ]
