# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2.0

workflows:
  version: 2
  build-and-deploy-test:
    jobs:
      - build
      - deployment:
          filters:
            branches:
              only: Auto_Deploy_Test
          requires:
            - build

jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.7.0
      - image: circleci/postgres:10.5

    working_directory: ~/repo

    steps:

      - attach_workspace:
          at: ~/circleci-demo-workflows
      
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Activate virtual environment and install project
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            nodeenv -p --node=8.11.4
            npm install ava

      # Save everything to the workspace for deployment test
      - persist_to_workspace:
          root: .
          paths:
            - templates/

      # Cache dependencies using checksum of requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # Run application tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
            npm test

      # Store test reports
      - store_artifacts:
          path: test-reports
          destination: test-reports

  deployment:

    machine:
      enabled: true

    steps:

      # Server SSH key
      - add_ssh_keys:
          fingerprints:
            - "a3:e2:e1:16:45:1a:dd:fd:81:5d:31:18:a1:ff:cc:1c"

      # Refer to workspace defined in install step
      - attach_workspace:
          at: ~/test-deploy-workflow

      # Deployment test
      - run:
          name: Auto_Deploy_Test
          command: |
            cd ~/test-deploy-workflow && ls -a
            # ssh $SSH_USER@$SSH_HOST "mkdir Auto_Deploy_Test && cd Auto_Deploy_Test && echo 'Hello world' >> test.txt"
